# =============================================================================
# artisan: `php artisan serve` under supervisor (dev only).
# =============================================================================

services:
  app:
    ports:
      - '${APP_PORT:-8000}:8000'
    volumes:
      - '../config/supervisor/server-artisan.conf:/etc/supervisor/programs/20-server.conf:ro'
