services:

  # Proxy server
  caddy:
    restart: '${RESTART_POLICY}'
    image: caddy:latest
    container_name: '${CONTAINER_NAME}-caddy'
    depends_on:
      - app
    networks:
      - app-network
    ports:
      - '80:80'
      - "443:443"
    volumes:
      - '../../:/var/www/${CONTAINER_NAME}'
      - '${STORAGE_MOUNT_PATH:-./storage}:/var/www/${CONTAINER_NAME}/storage'
      - '../Caddyfile:/etc/caddy/Caddyfile'
      - 'caddy_data:/data'  # DO NOT REMOVE IN ORDER TO PREVENT BEING RATE LIMITED WE STORE CERTIFICATES PERSISTENTLY
      - 'caddy_config:/config'
volumes:
  caddy_data:
  caddy_config:
