services:
  meilisearch:
    container_name: ${CONTAINER_NAME}-meilisearch
    image: getmeili/meilisearch:v1.5.0
    environment:
      - TZ=Europe/Rome
      - MEILI_MASTER_KEY=${MEILISEARCH_KEY}
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
      - MEILI_ENV=${MEILI_ENV:-development}
      - MEILI_LOG_LEVEL
      - MEILI_DB_PATH=/data.ms
    #        ports:
    #            - 8113:7700 # do not expose meilisearch port to the outside world
    networks:
      - app-network
    volumes:
      - ${MEILI_DB_PATH:-./meilisearch}:/data.ms
    restart: unless-stopped
