services:
  nginx-rtmp:
    image: tiangolo/nginx-rtmp
    networks:
      - app-network
    container_name: ${CONTAINER_NAME}-nginx-rtmp
    ports:
      - "1935:1935"  # RTMP port
      - "8081:80"    # HTTP port
    volumes:
      - ../../public/assets/videos/rtmp:/var/www/videos  # Volume for storing video files
      - ../../public/assets/videos/hls:/var/www/hls  # Volume for storing HLS files
      - ../nginx-rtmp.conf:/etc/nginx/nginx.conf  # Mount your custom Nginx configuration
    restart: unless-stopped

