# =============================================================================
# Soketi Service
# Open-source WebSocket server (Pusher-compatible)
# =============================================================================

services:
  soketi:
    container_name: '${CONTAINER_NAME}-soketi'
    image: 'quay.io/soketi/soketi:latest-16-alpine'
    restart: '${RESTART_POLICY:-no}'
    ports:
      - '${SOKETI_PORT:-6001}:6001'
    environment:
      - SOKETI_DEFAULT_APP_ID=${PUSHER_APP_ID:-some-id}
      - SOKETI_DEFAULT_APP_KEY=${PUSHER_APP_KEY:-app-key}
      - SOKETI_DEFAULT_APP_SECRET=${PUSHER_APP_SECRET:-some-app-secret}
    networks:
      - app-network
